config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users/created_events/', to: 'users#my_events'
  post '/attendee_event/', to:'attendee_event#create'
  delete '/attendee_event/', to:'attendee_event#destroy'
  post '/invitations/', to: 'invitations#create'
  resources :events
  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee_event.rb
class AttendeeEvent < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"

  has_many :attendee_events, dependent: :destroy
  has_many :attendees, through: :attendee_events 

  has_many :invitations, dependent: :destroy
  has_many :guests, through: :invitations

  scope :past, -> {where("event_date < ?",Date.today)}
  scope :upcomming, -> {where("event_date >= ?",Date.today)}

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :guest, class_name: "User"
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :created_events, foreign_key: :creator_id, class_name: "Event"

  has_many :attendee_events, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendee_events, source: :event

  has_many :invitations, foreign_key: :guest_id, dependent: :destroy
  has_many :events_invitations, through: :invitations, source: :event

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendee_event_controller.rb
class AttendeeEventController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create]
  def create
    @attev = current_user.attendee_events.build({event_id: params[:id]})
    if @attev.save
      redirect_back(fallback_location: root_path)
    else
      puts @attev.errors.full_messages
      redirect_back(fallback_location: root_path)
    end
  end
  def destroy
    @attev = current_user.attendee_events.find_by({event_id: params[:id]}).destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :verify_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user! , only: [:new, :create]
  def new
    @event = Event.new
  end
  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to new_event_path
    else
      puts @event.errors.full_messages
      render :new
    end
  end
  def index
    @events = Event.all
  end
  def show
    @event = Event.find(params[:id])
  end
  def edit
  end
  def update
    if @event.update(event_params)
      redirect_to users_created_events_path
    else
      render :edit 
    end
  end
  def destroy
    @event.destroy
    redirect_to users_created_events_path
  end

  def verify_user
    @event = current_user.created_events.find(params[:id])
    redirect_to events_path, notice: "Not Authorized To Edit This Event" if @event.nil?
  end

  private
  def event_params
    params.require(:event).permit(:event_date, :title)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create]
  def create
    event = current_user.created_events.find(params[:event_id])
    if not event.nil? and event.invitations.build(guest_id: User.find_by(email: params[:email]).id).save
      redirect_to events_path + "/" + params[:event_id]
    end
  end
  #def invitation_params
  #  params.require(:event).permit(:event_date, :title)
  #end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create]
  def my_events
    @user = current_user 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendee_event_helper.rb
module AttendeeEventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/attendee_event/create.html.erb
<h1>AttendeeEvent#create</h1>
<p>Find me in app/views/attendee_event/create.html.erb</p>

app/views/events/edit.html.erb
<h1>Event Edit</h1>

<%= form_with model: @event do |form| %>
  <%= form.label :title, "Title of the Event" %> <br>
  <%= form.text_field :title, placeholder: "Title" %> <br><br>
  <%= form.label :event_date, "Date of the Event" %> <br>
  <%= form.date_field :event_date %> <br><br>
  <%= form.submit %> <br>
<% end %>

app/views/events/index.html.erb
<h1>Events</h1>
<section>
  <h2>Past</h2>
  <% @events.past.each do |event| %>
    <article>
      <strong>Title:</strong> <%= event.title %>
      <br>
      <strong>Event-Date</strong> <%= event.event_date %>
      <br>
      <strong>Creator's Email:</strong> <%= event.creator.email %>
      <br>
      <strong>Attendees:</strong>
      <ul>
        <% event.attendees.each do |user| %>
          <li>Id:<%= user.id %> Email:<%= user.email %></li>
        <% end %>
      </ul>
    </article>
  <% end %>
</section>
<section>
  <h2>Upcomming</h2>
  <% @events.upcomming.each do |event| %>
    <article>
      <strong>Title:</strong> <%= event.title %>
      <br>
      <strong>Event-Date</strong> <%= event.event_date %>
      <br>
      <strong>Creator's Email:</strong> <%= event.creator.email %>
      <br>
      <strong>Attendees:</strong>
      <ul>
        <% event.attendees.each do |user| %>
          <li>Id:<%= user.id %> Email:<%= user.email %></li>
        <% end %>
      </ul>
      <br>
      <% if user_signed_in? %>
        <% if event.creator == current_user || event.guests.any? { | guest | guest == current_user } %>
          <% if event.attendees.to_a.none? { |user| user.id == current_user.id } %>
            <em>You were invited to this event!!</em>
            <%= button_to "Attend this Event", attendee_event_path({id: event.id}), method: :post %>
          <% else %>
            <em>You will attend this event!!</em>
            <%= button_to "Unattend this Event", attendee_event_path({id: event.id}), method: :delete %>
          <% end %>
        <%= link_to "Show", event_path(event) %>
        <% end %>
      <% end %>
    </article>
  <% end %>
</section>

app/views/events/new.html.erb
<h1>Event Creation</h1>

<%= form_with model: @event do |form| %>
  <%= form.label :title, "Title of the Event" %> <br>
  <%= form.text_field :title, placeholder: "Title" %> <br><br>
  <%= form.label :event_date, "Date of the Event" %> <br>
  <%= form.date_field :event_date %> <br><br>
  <%= form.submit %> <br>
<% end %>

app/views/events/show.html.erb
<h1>Event: <%= @event.title %></h1>
<br>
<strong>Event-Date:</strong> <%= @event.event_date %>
<br>
<strong>Creator's Email:</strong> <%= @event.creator.email %>
<br>
<strong>Attendees:</strong>
<ul>
  <% @event.attendees.each do |user| %>
    <li>Id:<%= user.id %> Email:<%= user.email %></li>
  <% end %>
</ul>
<strong>Guests</strong>
<ul>
  <% @event.guests.each do |user| %>
    <li>Id:<%= user.id %> Email:<%= user.email %></li>
  <% end %>
</ul>
<% if user_signed_in? %>
  <% if @event.creator == current_user || @event.guests.any? { | guest | guest == current_user } %>
    <% if @event.attendees.to_a.none? { |user| user.id == current_user.id } %>
      <%= button_to "Attend this Event", attendee_event_path({id: @event.id}), method: :post %>
    <% else %>
      <em>You will attend this event!!</em>
      <%= button_to "Unattend this Event", attendee_event_path({id: @event.id}), method: :delete %>
    <% end %>
  <% end %>
  <% if current_user.created_events.any? { |event| event.id == @event.id } %>
    <section>
      <h2>Invite a user to this event</h2>
      <%= form_with url: invitations_path do |form| %>
        <%= form.hidden_field :event_id, value: @event.id %>
        <%= form.label :email, "Insert the email of the user to invite" %> <br>
        <%= form.email_field :email, placeholder: "Email" %> <br><br>
        <%= form.submit "Invite User" %> <br>
      <% end %>
    </section>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav>
<%= link_to "Show Events", events_path %>
<%= link_to "Create Event", new_event_path %>
<% if user_signed_in? %>
  <%= link_to "My Created Events", "/users/created_events" %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_user_session_path %>
<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/users/my_events.html.erb
<h1>Events Created by <%= @user.email %></h1>
<section>
  <% @user.created_events.each do |event| %>
    <article>
      <strong>Title:</strong> <%= event.title %>
      <br>
      <strong>Event-Date</strong> <%= event.event_date %>
      <br>
      <strong>Creator's Email:</strong> <%= event.creator.email %>
      <% if user_signed_in? %>
        <% if event.creator == current_user || event.guests.any? { | guest | guest == current_user } %>
          <% if event.attendees.to_a.none? { |user| user.id == current_user.id } %>
            <%= button_to "Attend this Event", attendee_event_path({id: event.id}), method: :post %>
          <% else %>
            <em>You will attend this event!!</em>
            <%= button_to "Unattend this Event", attendee_event_path({id: event.id}), method: :delete %>
          <% end %>
        <% end %>
          <br>
        <%= link_to "Show", event_path(event) %>
        <% if event.creator == current_user %>
          <%= link_to "Edit", edit_event_path(event) %>
          <%= link_to "Delete", event_path(event), method: :delete %>
        <% end %>
      <% end %>
      <br>
      <strong>Attendees:</strong>
      <ul>
        <% event.attendees.each do |user| %>
          <li>Id:<%= user.id %> Email:<%= user.email %></li>
        <% end %>
      </ul>
    </article>
  <% end %>
</section>
<section>
  <br>
  <h2>Attended Events:</h2>
  <article>
    <strong>Past</strong>
    <ul>
      <% @user.attended_events.each do |event| %>
        <% if event.event_date < Date.today %>
          <li>Title: <%= event.title %> Event-date: <%= event.event_date %></li>
        <% end %>
      <% end %>
    </ul>
  </article>
  <article>
    <strong>Future</strong>
    <ul>
      <% @user.attended_events.each do |event| %>
        <% if event.event_date >= Date.today %>
          <li>Title: <%= event.title %> Event-date: <%= event.event_date %></li>
        <% end %>
      <% end %>
    </ul>
  </article>
</section>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Events Created by <%= @user.email %></h1>
<div>
  <% @user.created_events.each do |event| %>
    <div>
      <strong>Title:</strong> <%= event.title %>
      <br>
      <strong>Event-Date</strong> <%= event.event_date %>
      <br>
      <strong>Creator's Email:</strong> <%= event.creator.email %>
    </div>
    <% if user_signed_in? %>
      <% if event.attendees.to_a.none? { |user| user.id == current_user.id } %>
        <%= form_with url: "/attendee_event", method: :post do |form| %>
          <%= form.hidden_field :event_id, value: event.id %>
          <%= form.submit "Attend this Event" %>
        <% end %>
      <% else %>
        <em>You will attend this event!!</em>
      <% end %>
    <% end %>
    <br>
    <h2>Attendees:</h2>
    <ul>
      <% event.attendees.each do |user| %>
        <li>Id:<%= user.id %> Email:<%= user.email %></li>
      <% end %>
    </ul>
  <% end %>
    <br>
    <h2>Attended Events:</h2>
    <strong>Past</strong>
    <ul>
      <% @user.attended_events.each do |event| %>
        <% if event.event_date < Date.today %>
          <li>Title: <%= event.title %> Event-date: <%= event.event_date %></li>
        <% end %>
      <% end %>
    </ul>
    <strong>Future</strong>
    <ul>
      <% @user.attended_events.each do |event| %>
        <% if event.event_date >= Date.today %>
          <li>Title: <%= event.title %> Event-date: <%= event.event_date %></li>
        <% end %>
      <% end %>
    </ul>
</div>